### ISSUE TITLE
Cannot index string with string "title"

### ISSUE THREAD

**Issue by chicagoandy** [matt-FFFFFF/hassio-addon-repository#19]
New install, I appear to have Grafana, Mosquito, Postgres configured as instructed.  Getting the following error:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:29:49] INFO: Checking for Grafana folder: TeslaMate
jq: error (at <stdin>:1): Cannot index string with string "title"
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by chicagoandy** [comment]
Note, if I disable grafana_import_dashboards, I am able to launch TeslaMate.    But I'd like to see the dashboards, and I'm at a loss how to fix this.

**Comment by matt-FFFFFF** [comment]
This means that the teslamate addon cannot communicate with/log on to your grafana addon. Something is wrong with the hostname, username, password or port number.

`GF_SECURITY_ADMIN_USER` and `GF_SECURITY_ADMIN_PASSWORD` may only get set on the first run of Grafana. Try copying the grafana config, removing the addon and then re-installing it. Before starting it for the first time, paste in the config and you should be able to set the admin username and password.

**Comment by chicagoandy** [comment]
Thanks.   That helped, now I have all the plugins starting without errors.

But... what comes next?   I do not see any dashboards in Grafana.     I do see the three plugins installed.

**Comment by chicagoandy** [comment]
Thank you, that was helpful.   Likely the first-run problem you mentioned.
