### ISSUE TITLE
ELF not found

### ISSUE THREAD

**Issue by ackdom** [matt-FFFFFF/hassio-addon-repository#2]
Trying ro run this addon my hassio supervizor version 214. I am running it on Raspberry

default configuration nothing changed
Only thing in the log is ... 

/opt/app/erts-10.7/bin/erlexec: line 1: ELF: not found
/opt/app/erts-10.7/bin/erlexec: line 2: syntax error: unexpected "("

**Comment by matt-FFFFFF** [comment]
Hi

I used the native Home Assistant containers for cross compilation. I guess that didn't work as I've only been able to test amd64 versions.

I will look into why the cross compilation is not producing correct binaries.

**Comment by ackdom** [comment]
Is there any way I can help you? I guess I would have to try to build the docker image on the raspberry right? I dont have any spare one

**Comment by matt-FFFFFF** [comment]
Normally you cross compile these - so use a amd64 processor to produce a binary for arm. However this process has clearly not worked. I'll take a look at how it's done in the parent repo to see if I can replicate.

**Comment by matt-FFFFFF** [comment]
Reading further, there may be an environment variable that I can set to cross compile for a different target:

https://hexdocs.pm/mix/1.10.1/Mix.html#module-targets

**Comment by matt-FFFFFF** [comment]
I sent a mail to Adrian and he kindly responded, I'll see about porting his build method into this repo.

He uses docker buildx, and the following shell script: https://github.com/adriankumpf/teslamate/blob/master/bin/buildx.sh

Looks like I need to install qemu-user and then configure the multi-arch support like this:
* https://github.com/multiarch/qemu-user-static

Then make a builder: ```docker buildx create --use```

Then build the containers, labelling them correctly for HA

**Comment by matt-FFFFFF** [comment]
I have buildx working inside of GitHub Actions. I have also changed the way the containers are built so that they use the original teslamate images as a base.

I'll see if I can test this locally then update the main repo. Should be a few days.

**Comment by matt-FFFFFF** [comment]
Should now be fixed in v0.1.0 of the addon
