### ISSUE TITLE
Add TeslaMate dashboards to existing Grafana environment

### ISSUE THREAD

**Issue by TheDK** [matt-FFFFFF/hassio-addon-repository#24]
I already have Grafana set-up and would like TeslaMate to use this instance for the dashboards. Unfortunately, the guide says the env_vars need to be set before the first start of Grafana as they are only parsed on first start-up.

Is there any way to achieve this? Any way to set the variables manually on an existing installation? Or do I have to run an extra Grafana installation for TeslaMate?

**Comment by RikVerstijnen** [comment]
You can just perform the necessary setup manually in the Grafana GUI. Create a user in Home > Administration > Users. And add the corresponding details to the TeslaMate plugin configuration.

**Comment by TheDK** [comment]
During different tests it seems to me that it was not necessary to do this using env_vars and it's working just fine. :)
