### ISSUE TITLE
Awesome work!  (I just wish I'd found this sooner)

### ISSUE THREAD

**Issue by krelltunez** [matt-FFFFFF/hassio-addon-repository#6]
I was about to pull my hair out trying to get a Teslamate docker install on my QNAP NAS to talk to the HA MQTT broker add-on.  They appeared connected, but none of my sensors would update.  I've since disabled MQTT in Teslamate and was just about to give up, when I discovered this (it would be great to get this into HACS, so more people would know about it and use it!).

A couple questions before I try this out:

1. Is it possible to run two instances of this add-on?  My wife will soon be getting a Tesla on her own Tesla account; it would be nice to have all that data in HA.  Understood if not possible, as I know Teslamate is not intended to support multiple accounts.  Eventually, we may merge our accounts, but I wanted each of us to get the supercharging referral bonus.

2. Do you know if I'd be able to backup my data from my existing Teslamate install (2+ years of data) and restore it in this add-on?  I've done so before using [this guide](https://docs.teslamate.org/docs/maintenance/backup_restore), but I'm not sure how I'd do it here (I stumbled a few times figuring out how to do it in the QNAP environment).  Perhaps it would be possible through the Terminal & SSH add-on (I'd just have to figure out where docker-compose resides - assuming it actually exists)?

3. BONUS QUESTION... do you have a place where I could donate?  I've already donated to adriankumpf and would like to show my gratitude for your great work!!

Thanks... this is awesome stuff!

**Comment by matt-FFFFFF** [comment]
Hi, thanks for the comments 👍 

1. Yes, you could run two instances, however HA would need to see them as two unique addons - e.g. teslamate & teslamate2. For example, you could fork this repo and install the addon twice - once from here and once from your own repo. You'd need to change `slug` and `name` values in the [config.json](https://github.com/matt-FFFFFF/hassio-addon-repository/blob/master/teslamate/config.json). You could in theory use the same postgres instance and have different DBs but I haven't tried this out.

2. Yes, if you expose the postgres port externally in HA. You could use standard postgres tools to backup and restore data. Don't have TM running when you do this obvs.

3. I don't, no. Give any donation to a worthy cause :)

I'll investigate HACS and how to integrate with that - I didn't know it did addons too.

**Comment by krelltunez** [comment]
Cool, I'm going to try this over the next few weeks.

Regarding #3, maybe I'll send another donation adriankumpf's way... certainly a cause worth funding!

**Comment by matt-FFFFFF** [comment]
Looking at the Postgres addon, it is architected for a single DB at the moment so maybe run two instances of that as well :)

**Comment by matt-FFFFFF** [comment]
Re: donation - if you can get Adrian to implement this then we could use HA ingress :) https://github.com/adriankumpf/teslamate/issues/494
